global:
  scrape_interval: 15s
  evaluation_interval: 15s

# Alerting and Recording rules
rule_files:
  - /etc/prometheus/alerts.yml
  - /etc/prometheus/recording-rules.yml

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'vernemq'
    static_configs:
      - targets: ['vernemq:8888']
    metrics_path: /metrics

  - job_name: 'webhook-auth'
    static_configs:
      - targets: ['webhook-auth:80']
    metrics_path: /metrics
